##spring:
##  datasource:
##    driver-class-name: com.mysql.jdbc.Driver
##    username: root
##    password: root
##    url: jdbc:mysql://192.168.232.129:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
##  cloud:
##    nacos:
##      discovery:
##        server-addr: 192.168.232.129:8848
##mybatis-plus:
##  mapper-locations: classpath:/mapper/**/*.xml
##  global-config:
##    db-config:
##      id-type: auto
##server:
##  port: 4000
#
#logging:
#  level:
#    com.dadazhang.gulimall: debug
#
#spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#  thymeleaf:
#    cache: false
#  redis:
#    port: 6379
#    host: 192.168.240.128
#    database: 0
#    ssl: false
#  session:
#    store-type: redis
#server:
#  port: 4000
#
#gulimall:
#  thread:
#    pool:
#      code-pool-size: 50
#      maximum-pool-size: 300
#      keep-alive-time: 10
#
