apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gulimall-coupon
  name: gulimall-coupon
  namespace: gulimall
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: gulimall-coupon
  template:
    metadata:
      labels:
        app: gulimall-coupon
    spec:
      containers:
        - image: $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:latest
          imagePullPolicy: IfNotPresent
          name: gulimall-coupon
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: gulimall-coupon
  namespace: gulimall
  labels:
    app: gulimall-coupon
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003  #range 30000-32767
  selector:
    app: gulimall-coupon
  type: NodePort
  sessionAffinity: None