#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.240.128:8848
#  thymeleaf:
#    cache: false
#  redis:
#    host: 192.168.240.128
#    port: 6379
#  session:
#    store-type: redis
#
#server:
#  port: 8000
#  servlet:
#    session:
#      timeout: 30m