##spring:
##  datasource:
##    driver-class-name: com.mysql.jdbc.Driver
##    username: root
##    password: root
##    url: jdbc:mysql://192.168.232.129:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
##  application:
##    name: gulimall-order
##  cloud:
##    nacos:
##      discovery:
##        server-addr: 192.168.232.129:8848
##mybatis-plus:
##  mapper-locations: classpath:/mapper/**/*.xml
##  global-config:
##    db-config:
##      id-type: auto
##server:
##  port: 3000
#logging:
#  level:
#    com.dadazhang.gulimall: debug
#spring:
#  session:
#    store-type: redis
#  redis:
#    port: 6379
#    host: 192.168.240.128
#  thymeleaf:
#    cache: false
#  mvc:
#    format:
#      date: yyyy-MM-dd
##      date-time: yyyy-MM-dd HH:mm:ss